Para probar distintas matrices con este método se utilizará el paquete numpy. Notemos que para las matrices iniciales de 2x2 el método no requiere demasiadas iteraciones para converger a la matriz cuya diagonal son los valores propios de la matriz inicial. No obstante, cuando la matriz es de una dimensión mayor, el método llega al límite de las iteraciones para converger a la matriz mencionada. Notemos que el código busca que los resultados sean de tipo float, de modo que las aproximaciones, aunque cercanas, pueden traer problemas.

En los experimentos podemos evidenciar que para matrices "pequeñas" el método converge en pocas iteraciones; no obstante, aunque para matrices de mayor dimensión el método requiere un número grande de iteraciones, lo cierto es que converge con mucha precisión a los resultados, de modo que podría aumentarse las iteraciones y agregar cierto tipo de criterios (perturbación en las matrices modificadas, por ejemplo; tolerancia menor; computadores más veloces; etc.) para que la convergencia sea aún más precisa.



In [ ]:
import numpy as np
from numpy.linalg import qr

def QR_Iteracion(A, tol=1e-6, max_iter=1000):
    #Definimos la función con una matriz inicial cuadrada, una tolerancia estándar y un número máximo de iteraciones estándar

    # Esta función va a retornar a la matriz A después de las iteraciones y cuántas iteraciones fueron necesarias

    # Copia inicial de la matriz
    A_actual = np.array(A, dtype=float)

    for iteracion in range(max_iter):
        # Hacemos el primer paso de descomposición QR, incluido en el paquete de Python
        Q, R = np.linalg.qr(A_actual)

        # Actualizamos la matriz usando Q y R multiplicándolas en el orden inverso para generar la siguiente iteración
        A_nueva = R @ Q

        # Verificamos la norma de Froebenius de la matriz obtenida, norma que nos permite comparar todas las entradas de las matrices, y aumentamos la iteración
        if np.linalg.norm(A_nueva - A_actual, ord='fro') < tol:
            return A_nueva, iteracion + 1

        # Actualizar A para la siguiente iteración
        A_actual = A_nueva

    # Si no converge, devolver el resultado actual; si converge, devolver los elementos de la diagonal de la matriz de convergencia, el número de iteraciones y los valores y vectores propios de dicha matriz
    return np.diag(A_actual), max_iter, np.linalg.eig(A_actual)

In [ ]:
A = np.matrix([[2, 1], [3, 4]])

QR_Iteracion(A, tol=1e-6, max_iter=1000)

In [ ]:
A = np.matrix([[3, 2], [3,4]])

QR_Iteracion(A, tol=1e-6, max_iter=1000)

(array([[6., 1.],
        [0., 1.]]),
 418)

In [ ]:
A = np.matrix([[1, 1, 2], [2, 1, 1], [1, 1, 3]])

QR_Iteracion(A, tol=1e-6, max_iter=1000)

(array([ 4.50701864,  0.77812384, -0.28514248]),
 1000,
 EigResult(eigenvalues=array([ 4.50701864,  0.77812384, -0.28514248]), eigenvectors=array([[1.        , 0.19716465, 0.08857273],
        [0.        , 0.98037039, 0.74074701],
        [0.        , 0.        , 0.66591947]])))

In [ ]:
A = np.matrix([[1, 1, 2], [2, 1, 3], [1, 1, 1]])

QR_Iteracion(A, tol=1e-6, max_iter=1000)

(array([ 4.04891734, -0.69202147, -0.35689587]),
 1000,
 EigResult(eigenvalues=array([ 4.04891734, -0.69202147, -0.35689587]), eigenvectors=array([[ 1.        ,  0.45086709, -0.08763476],
        [ 0.        ,  0.8925911 , -0.35509341],
        [ 0.        ,  0.        ,  0.93071414]])))

In [ ]:
A = np.matrix([[1, 1, 1, 2], [2, 1, 1, 1], [3, 2, 1, 2],  [2, 1, 1, 4]])

QR_Iteracion(A, tol=1e-6, max_iter=1000)

(array([ 6.63453446,  1.50856334, -0.73564154, -0.40745627]),
 1000,
 EigResult(eigenvalues=array([ 6.63453446,  1.50856334, -0.73564154, -0.40745627]), eigenvectors=array([[ 1.        ,  0.22416801,  0.28255545, -0.05762194],
        [ 0.        ,  0.97455051,  0.43966827,  0.08477969],
        [ 0.        ,  0.        ,  0.85255747,  0.22268066],
        [ 0.        ,  0.        ,  0.        ,  0.9694872 ]])))

In [ ]:
A = np.matrix([[1, 2, 1, 2], [2, 1, 1, 1], [3, 2, 1, 2],  [2, 1, 1, 4]])

QR_Iteracion(A, tol=1e-6, max_iter=1000)

(array([ 6.82726225,  1.72811591, -1.08793492, -0.46744323]),
 1000,
 EigResult(eigenvalues=array([ 6.82726225,  1.72811591, -1.08793492, -0.46744323]), eigenvectors=array([[ 1.        , -0.15398976,  0.20691394,  0.29609595],
        [ 0.        ,  0.98807244, -0.21970509, -0.28719298],
        [ 0.        ,  0.        ,  0.95337102,  0.57975337],
        [ 0.        ,  0.        ,  0.        ,  0.70266166]])))

In [ ]:
A = np.matrix([[1, 2, 1, 2], [2, 1, 1, 1], [3, 2, 1, 2],  [2, 1, 1, 4]])

QR_Iteracion(A, tol=1e-6, max_iter=1000)

(array([ 6.82726225,  1.72811591, -1.08793492, -0.46744323]),
 1000,
 EigResult(eigenvalues=array([ 6.82726225,  1.72811591, -1.08793492, -0.46744323]), eigenvectors=array([[ 1.        , -0.15398976,  0.20691394,  0.29609595],
        [ 0.        ,  0.98807244, -0.21970509, -0.28719298],
        [ 0.        ,  0.        ,  0.95337102,  0.57975337],
        [ 0.        ,  0.        ,  0.        ,  0.70266166]])))