In [ ]:
A = np.matrix([[2, 1], [3, 4]])

QR_Iteracion(A, tol=1e-6, max_iter=1000)

(array([[ 5., -2.],
        [ 0.,  1.]]),
 465)

In [ ]:
A = np.matrix([[3, 2], [3,4]])

QR_Iteracion(A, tol=1e-6, max_iter=1000)

(array([[6., 1.],
        [0., 1.]]),
 418)

In [ ]:
A = np.matrix([[1, 1, 2], [2, 1, 1], [1, 1, 3]])

QR_Iteracion(A, tol=1e-6, max_iter=1000)

(array([ 4.50701864,  0.77812384, -0.28514248]),
 1000,
 EigResult(eigenvalues=array([ 4.50701864,  0.77812384, -0.28514248]), eigenvectors=array([[1.        , 0.19716465, 0.08857273],
        [0.        , 0.98037039, 0.74074701],
        [0.        , 0.        , 0.66591947]])))

In [ ]:
A = np.matrix([[1, 1, 2], [2, 1, 3], [1, 1, 1]])

QR_Iteracion(A, tol=1e-6, max_iter=1000)

(array([ 4.04891734, -0.69202147, -0.35689587]),
 1000,
 EigResult(eigenvalues=array([ 4.04891734, -0.69202147, -0.35689587]), eigenvectors=array([[ 1.        ,  0.45086709, -0.08763476],
        [ 0.        ,  0.8925911 , -0.35509341],
        [ 0.        ,  0.        ,  0.93071414]])))

In [ ]:
A = np.matrix([[1, 1, 1, 2], [2, 1, 1, 1], [3, 2, 1, 2],  [2, 1, 1, 4]])

QR_Iteracion(A, tol=1e-6, max_iter=1000)

(array([ 6.63453446,  1.50856334, -0.73564154, -0.40745627]),
 1000,
 EigResult(eigenvalues=array([ 6.63453446,  1.50856334, -0.73564154, -0.40745627]), eigenvectors=array([[ 1.        ,  0.22416801,  0.28255545, -0.05762194],
        [ 0.        ,  0.97455051,  0.43966827,  0.08477969],
        [ 0.        ,  0.        ,  0.85255747,  0.22268066],
        [ 0.        ,  0.        ,  0.        ,  0.9694872 ]])))

In [ ]:
A = np.matrix([[1, 2, 1, 2], [2, 1, 1, 1], [3, 2, 1, 2],  [2, 1, 1, 4]])

QR_Iteracion(A, tol=1e-6, max_iter=1000)

(array([ 6.82726225,  1.72811591, -1.08793492, -0.46744323]),
 1000,
 EigResult(eigenvalues=array([ 6.82726225,  1.72811591, -1.08793492, -0.46744323]), eigenvectors=array([[ 1.        , -0.15398976,  0.20691394,  0.29609595],
        [ 0.        ,  0.98807244, -0.21970509, -0.28719298],
        [ 0.        ,  0.        ,  0.95337102,  0.57975337],
        [ 0.        ,  0.        ,  0.        ,  0.70266166]])))

In [ ]:
A = np.matrix([[1, 2, 1, 2], [2, 1, 1, 1], [3, 2, 1, 2],  [2, 1, 1, 4]])

QR_Iteracion(A, tol=1e-6, max_iter=1000)

(array([ 6.82726225,  1.72811591, -1.08793492, -0.46744323]),
 1000,
 EigResult(eigenvalues=array([ 6.82726225,  1.72811591, -1.08793492, -0.46744323]), eigenvectors=array([[ 1.        , -0.15398976,  0.20691394,  0.29609595],
        [ 0.        ,  0.98807244, -0.21970509, -0.28719298],
        [ 0.        ,  0.        ,  0.95337102,  0.57975337],
        [ 0.        ,  0.        ,  0.        ,  0.70266166]])))